CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    repo_path TEXT NOT NULL,
    dockerfile_path TEXT DEFAULT 'Dockerfile', compose_file TEXT DEFAULT 'docker-compose.yml',
    image_name TEXT NOT NULL, ssh_host TEXT DEFAULT '', deploy_dir TEXT NOT NULL,
    health_url TEXT DEFAULT '', health_container TEXT DEFAULT '', build_args TEXT DEFAULT '{}',
    compose_services TEXT DEFAULT 'app worker', git_pull_before_build BOOLEAN DEFAULT TRUE,
    runner_id BIGINT DEFAULT 0, deploy_mode TEXT DEFAULT 'docker', post_deploy TEXT DEFAULT '',
    permissions TEXT DEFAULT '', preserve TEXT DEFAULT '', created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE builds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id), status TEXT NOT NULL DEFAULT 'running',
    commit_sha TEXT DEFAULT '', started_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ, duration_seconds INTEGER, log TEXT DEFAULT '', error_message TEXT DEFAULT '',
    error_code TEXT DEFAULT '', triggered_by TEXT DEFAULT 'manual'
);
CREATE TABLE runners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE,
    token TEXT NOT NULL UNIQUE, labels TEXT DEFAULT '', status TEXT DEFAULT 'offline',
    last_seen TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    build_id BIGINT NOT NULL REFERENCES builds(id), runner_id BIGINT NOT NULL REFERENCES runners(id),
    status TEXT DEFAULT 'pending', artifact_path TEXT DEFAULT '', deploy_dir TEXT DEFAULT '',
    compose_file TEXT DEFAULT 'docker-compose.yml', compose_services TEXT DEFAULT '', image_name TEXT DEFAULT '',
    health_url TEXT DEFAULT '', health_container TEXT DEFAULT '', mode TEXT DEFAULT 'docker',
    post_deploy TEXT DEFAULT '', permissions TEXT DEFAULT '', preserve TEXT DEFAULT '', error_code TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, picked_at TIMESTAMPTZ, completed_at TIMESTAMPTZ
);
CREATE TABLE build_annotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    build_id BIGINT NOT NULL REFERENCES builds(id) ON DELETE CASCADE,
    note TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX idx_builds_one_running_per_project ON builds(project_id) WHERE status='running';
