ALTER TABLE runners ADD COLUMN IF NOT EXISTS active_task_kind TEXT NOT NULL DEFAULT '';
ALTER TABLE runners ADD COLUMN IF NOT EXISTS active_task_id BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS runner_telemetry (
    runner_id BIGINT PRIMARY KEY REFERENCES runners(id) ON DELETE CASCADE,
    agent_version TEXT NOT NULL DEFAULT '', hostname TEXT NOT NULL DEFAULT '', os_name TEXT NOT NULL DEFAULT '',
    uptime_seconds BIGINT NOT NULL DEFAULT 0, disk_total_bytes BIGINT NOT NULL DEFAULT 0,
    disk_free_bytes BIGINT NOT NULL DEFAULT 0, docker_available BOOLEAN NOT NULL DEFAULT FALSE,
    docker_version TEXT NOT NULL DEFAULT '', updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS runner_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    runner_id BIGINT NOT NULL REFERENCES runners(id), project_id BIGINT NOT NULL REFERENCES projects(id),
    kind TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', deploy_dir TEXT NOT NULL DEFAULT '',
    compose_file TEXT NOT NULL DEFAULT '', compose_services TEXT NOT NULL DEFAULT '', health_url TEXT NOT NULL DEFAULT '',
    health_container TEXT NOT NULL DEFAULT '', requested_by TEXT NOT NULL DEFAULT 'admin', result_summary TEXT NOT NULL DEFAULT '',
    log TEXT NOT NULL DEFAULT '', requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_runner_operations_queue ON runner_operations(runner_id, status, requested_at);
