CREATE TABLE notification_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id TEXT NOT NULL,
    name TEXT NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('browser', 'discord', 'slack', 'webhook')),
    endpoint_cipher TEXT NOT NULL DEFAULT '',
    browser_id TEXT NOT NULL DEFAULT '',
    project_ids JSONB NOT NULL DEFAULT '[]',
    events JSONB NOT NULL DEFAULT '["failed"]',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX notification_channels_owner ON notification_channels(owner_id, id);

CREATE TABLE notification_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL REFERENCES notification_channels(id) ON DELETE CASCADE,
    build_id BIGINT REFERENCES builds(id) ON DELETE CASCADE,
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_until TIMESTAMPTZ,
    last_error TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_at TIMESTAMPTZ,
    UNIQUE(channel_id, build_id)
);
CREATE INDEX notification_delivery_queue ON notification_deliveries(status, next_attempt_at);
-- Existing history must not trigger thousands of notifications on cutover.
ALTER TABLE builds ADD COLUMN notifications_recorded BOOLEAN NOT NULL DEFAULT TRUE;
CREATE INDEX builds_notification_pending ON builds(id) WHERE notifications_recorded=FALSE;
